//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Cutter3DImages
{
    public int ID { get; set; }
    public Nullable<int> ClassID { get; set; }
    public string UserName { get; set; }
    public string Name { get; set; }
    public string ImagePath { get; set; }
}

public partial class CutterClass
{
    public CutterClass()
    {
        this.Cutters = new HashSet<Cutters>();
    }

    public int ID { get; set; }
    public string Name { get; set; }

    public virtual ICollection<Cutters> Cutters { get; set; }
}

public partial class CutterDetailClass
{
    public CutterDetailClass()
    {
        this.Cutters = new HashSet<Cutters>();
    }

    public int ID { get; set; }
    public Nullable<int> ClassID { get; set; }
    public string UserName { get; set; }
    public string Name { get; set; }

    public virtual ICollection<Cutters> Cutters { get; set; }
}

public partial class CutterElectricTestRecord
{
    public int ID { get; set; }
    public Nullable<int> ElectricTestRecordID { get; set; }
    public Nullable<System.DateTime> DateTime { get; set; }
    public Nullable<double> Value { get; set; }
    public string TestLocation { get; set; }
    public Nullable<double> DangerousValue { get; set; }
}

public partial class CutterEvents
{
    public CutterEvents()
    {
        this.CuttersDetail = new HashSet<CuttersDetail>();
    }

    public int ID { get; set; }
    public string Event { get; set; }

    public virtual ICollection<CuttersDetail> CuttersDetail { get; set; }
}

public partial class CutterImages
{
    public int ID { get; set; }
    public Nullable<int> ImageID { get; set; }
    public Nullable<System.DateTime> DateTime { get; set; }
    public string ImagePath { get; set; }
}

public partial class CutterMaterial
{
    public CutterMaterial()
    {
        this.Cutters = new HashSet<Cutters>();
    }

    public int ID { get; set; }
    public string Name { get; set; }

    public virtual ICollection<Cutters> Cutters { get; set; }
}

public partial class CutterNotes
{
    public CutterNotes()
    {
        this.CuttersDetail = new HashSet<CuttersDetail>();
    }

    public int ID { get; set; }
    public string Note { get; set; }

    public virtual ICollection<CuttersDetail> CuttersDetail { get; set; }
}

public partial class Cutters
{
    public System.Guid ID { get; set; }
    public string number { get; set; }
    public Nullable<int> ClassID { get; set; }
    public Nullable<int> DetailClassID { get; set; }
    public Nullable<int> MaterialID { get; set; }

    public virtual CutterClass CutterClass { get; set; }
    public virtual CutterDetailClass CutterDetailClass { get; set; }
    public virtual CutterMaterial CutterMaterial { get; set; }
    public virtual CuttersDetail CuttersDetail { get; set; }
}

public partial class CuttersDetail
{
    public System.Guid ID { get; set; }
    public Nullable<int> UsersGroupID { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public Nullable<System.DateTime> LastUseDate { get; set; }
    public Nullable<int> ExpectLife { get; set; }
    public Nullable<double> WearProcess { get; set; }
    public Nullable<int> WorkStatusID { get; set; }
    public Nullable<System.DateTime> StartTime { get; set; }
    public Nullable<System.DateTime> StopTime { get; set; }
    public string Location { get; set; }
    public Nullable<int> NoteID { get; set; }
    public Nullable<int> EventID { get; set; }
    public Nullable<int> ElectricTestRecordID { get; set; }
    public Nullable<int> Cutter3DImageID { get; set; }
    public Nullable<int> ImageID { get; set; }

    public virtual Cutters Cutters { get; set; }
    public virtual CutterWorkStatus CutterWorkStatus { get; set; }
    public virtual CutterEvents CutterEvents { get; set; }
    public virtual CutterNotes CutterNotes { get; set; }
}

public partial class CuttersInfo
{
    public System.Guid ID { get; set; }
    public string 模型图 { get; set; }
    public string 编号 { get; set; }
    public string 类别 { get; set; }
    public string 详细类别 { get; set; }
    public string 材料 { get; set; }
    public string 实物图 { get; set; }
    public Nullable<System.DateTime> 拍摄时间 { get; set; }
    public Nullable<System.DateTime> 添加日期 { get; set; }
    public Nullable<System.DateTime> 活跃日期 { get; set; }
    public Nullable<int> 预期寿命 { get; set; }
    public Nullable<double> 磨损进度 { get; set; }
}

public partial class CutterUsersGroup
{
    public int ID { get; set; }
    public Nullable<int> GroupID { get; set; }
    public string UserName { get; set; }
}

public partial class CutterWorkStatus
{
    public CutterWorkStatus()
    {
        this.CuttersDetail = new HashSet<CuttersDetail>();
    }

    public int ID { get; set; }
    public string Name { get; set; }

    public virtual ICollection<CuttersDetail> CuttersDetail { get; set; }
}

public partial class PersonalInfo
{
    public string 用户名 { get; set; }
    public string 权限 { get; set; }
    public string 邮箱 { get; set; }
    public System.DateTime 活跃 { get; set; }
}

public partial class Users
{
    public System.Guid UserId { get; set; }
    public System.Guid ApplicationId { get; set; }
    public string UserName { get; set; }
    public bool IsAnonymous { get; set; }
    public System.DateTime LastActivityDate { get; set; }
}
