//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class CMSDB_Entities : DbContext
{
    public CMSDB_Entities()
        : base("name=CMSDB_Entities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Users> Users { get; set; }
    public DbSet<CutterClass> CutterClass { get; set; }
    public DbSet<CutterImages> CutterImages { get; set; }
    public DbSet<CutterMaterial> CutterMaterial { get; set; }
    public DbSet<CutterUsersGroup> CutterUsersGroup { get; set; }
    public DbSet<CutterDetailClass> CutterDetailClass { get; set; }
    public DbSet<Cutters> Cutters { get; set; }
    public DbSet<Cutter3DImages> Cutter3DImages { get; set; }
    public DbSet<PersonalInfo> PersonalInfo { get; set; }
    public DbSet<CutterElectricTestRecord> CutterElectricTestRecord { get; set; }
    public DbSet<CutterWorkStatus> CutterWorkStatus { get; set; }
    public DbSet<CuttersDetail> CuttersDetail { get; set; }
    public DbSet<CutterEvents> CutterEvents { get; set; }
    public DbSet<CutterNotes> CutterNotes { get; set; }
    public DbSet<CuttersInfo> CuttersInfo { get; set; }
}
